git push origin main
name: CI

on:
  push:

jobs:
  deploy:
    uses: Nico-Chacon/Chacon-SharedWorkflows/.github/workflows/deploy-api.yaml@pipeTest
    with:
      image-name: mi-api-academica
      image-tag: v1.0.0
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}